  name: Tests
  on: [push, pull_request]
  
  jobs:
    test:
      runs-on: ubuntu-latest
      services:
        db:
          image: postgres:latest
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: messages
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 2s
            --health-timeout 5s
            --health-retries 5
      env:
        DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/messages
  
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: "3.12"
        - run: pip install -r requirements-test.txt
        - run: alembic upgrade head
        - run: pytest test/ -v
  
